package com.example.sqlite.db.schema

object MyProductSchema {

    const val TABLE_NAME = "my_product"

    const val COLUMN_ID = "id"
    const val COLUMN_PRODUCT_ID = "product_id"
    const val COLUMN_LAST_PRODUCT_EPISODE_ID = "last_product_episode_id"
    const val COLUMN_LAST_PRODUCT_EPISODE_TITLE = "last_product_episode_title"
    const val COLUMN_TICKET_TOTAL_COUNT = "ticket_total_count"
    const val COLUMN_WAIT_FREE_TICKET_START_CHARGED_AT = "wait_free_ticket_start_charged_at"
    const val COLUMN_WAIT_FREE_TICKET_FINISH_CHARGED_AT = "wait_free_ticket_finish_charged_at"
    const val COLUMN_WAIT_FREE_EPISODE_COUNT = "wait_free_episode_count"
    const val COLUMN_WAIT_FREE_EPISODE_READ_COUNT = "wait_free_episode_read_count"
    const val COLUMN_NOW_FREE_NEXT_META_INFO = "now_free_next_meta_info"
    const val COLUMN_NOW_FREE_NEXT_READ_AT = "now_free_next_read_at"
    const val COLUMN_NOW_FREE_OPEN_STATUS_FINISH_DAYS = "now_free_open_status_finish_days"
    const val COLUMN_IS_TICKET_CONSUMED_MY_PRODUCT_FLAG = "is_ticket_cunsumed_my_product_flag"
    const val COLUMN_LAST_PURCHASED_AT = "last_purchased_at"
    const val COLUMN_BOOKMARKED_AT = "bookmarked_at"
    const val COLUMN_USER_CONSUMED_TICKET_PRODUCT_EPISODE_INFO_LAST_SYNC_TIME =
        "user_consumed_ticket_product_episode_info_last_sync_time"
    const val COLUMN_PRODUCT_EPISODE_LIST_SORT_INFO = "product_episode_list_sort_info"
    const val COLUMN_LOCAL_PUSH_STATUS = "local_push_status"
    const val COLUMN_LOCAL_HISTORY_STATUS = "local_history_status"
    const val COLUMN_TICKET_CONSUMED_MY_PRODUCT_STATUS = "ticket_cunsumed_my_product_status"
    const val COLUMN_JSON_TEXT = "json_text"
    const val COLUMN_STATUS = "status"
    const val COLUMN_SORT_VALUE_LIST_UPDATED_ASC = "sort_value_list_updated_asc"
    const val COLUMN_FLAG_FETCH_SORT_VALUE_LIST_UPDATED_ASC =
        "flag_fetch_sort_value_list_updated_asc"
    const val COLUMN_UPDATED_AT = "updated_at"

    const val CREATE_TABLE = """CREATE TABLE IF NOT EXISTS 
        $TABLE_NAME  (
            $COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT, 
            $COLUMN_PRODUCT_ID INTEGER NOT NULL, 
            $COLUMN_LAST_PRODUCT_EPISODE_ID INTEGER,
            $COLUMN_LAST_PRODUCT_EPISODE_TITLE TEXT,
            $COLUMN_TICKET_TOTAL_COUNT INTEGER,
            $COLUMN_WAIT_FREE_TICKET_START_CHARGED_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
            $COLUMN_WAIT_FREE_TICKET_FINISH_CHARGED_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
            $COLUMN_WAIT_FREE_EPISODE_COUNT INTEGER NOT NULL DEFAULT -1,
            $COLUMN_WAIT_FREE_EPISODE_READ_COUNT INTEGER NOT NULL DEFAULT -2,
            $COLUMN_NOW_FREE_NEXT_META_INFO TEXT DEFAULT '',
            $COLUMN_NOW_FREE_NEXT_READ_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
            $COLUMN_NOW_FREE_OPEN_STATUS_FINISH_DAYS INTEGER NOT NULL DEFAULT 0,
            $COLUMN_IS_TICKET_CONSUMED_MY_PRODUCT_FLAG INTEGER NOT NULL DEFAULT 0,
            $COLUMN_LAST_PURCHASED_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
            $COLUMN_BOOKMARKED_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
            $COLUMN_USER_CONSUMED_TICKET_PRODUCT_EPISODE_INFO_LAST_SYNC_TIME DATETIME NOT NULL DEFAULT '1999-01-01 00:00:00',
            $COLUMN_PRODUCT_EPISODE_LIST_SORT_INFO INTEGER NOT NULL DEFAULT 1,
            $COLUMN_LOCAL_PUSH_STATUS INTEGER NOT NULL DEFAULT 1,
            $COLUMN_LOCAL_HISTORY_STATUS INTEGER NOT NULL DEFAULT 0,
            $COLUMN_TICKET_CONSUMED_MY_PRODUCT_STATUS INTEGER NOT NULL DEFAULT 0,
            $COLUMN_JSON_TEXT TEXT,
            $COLUMN_STATUS INTEGER NOT NULL, 
            $COLUMN_SORT_VALUE_LIST_UPDATED_ASC INTEGER NOT NULL DEFAULT 0,
            $COLUMN_FLAG_FETCH_SORT_VALUE_LIST_UPDATED_ASC INTEGER NOT NULL DEFAULT 0,
            $COLUMN_UPDATED_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
            UNIQUE (`$COLUMN_PRODUCT_ID`)
        );"""

    const val ALTER_TABLE_BOOKMARKED_AT_VER_200 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN $COLUMN_BOOKMARKED_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'"


    const val ALTER_TABLE_WAIT_FREE_EPISODE_COUNT_VER_211 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN $COLUMN_WAIT_FREE_EPISODE_COUNT INTEGER NOT NULL DEFAULT -"


    const val ALTER_TABLE_WAIT_FREE_EPISODE_READ_COUNT_VER_211 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN $COLUMN_WAIT_FREE_EPISODE_READ_COUNT INTEGER NOT NULL DEFAULT -2"

    const val ALTER_TABLE_TICKET_TOTAL_COUNT_VER_250 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN $COLUMN_TICKET_TOTAL_COUNT INTEGER NOT NULL DEFAULT 0"

    const val ALTER_TABLE_NOW_FREE_NEXT_META_INFO_VER_380 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN $COLUMN_NOW_FREE_NEXT_META_INFO TEXT NOT NULL DEFAULT ''"

    const val ALTER_TABLE_NOW_FREE_NEXT_READ_AT_VER_380 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN now_free_next_read_at DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'"

    const val ALTER_TABLE_NOW_FREE_OPEN_STATUS_FINISH_DAYS_VER_380 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN $COLUMN_NOW_FREE_OPEN_STATUS_FINISH_DAYS INTEGER NOT NULL DEFAULT 0"


    const val ALTER_TABLE_LAST_PURCHASED_AT_VER_390 =
        "ALTER TABLE $TABLE_NAME ADD COLUMN $COLUMN_LAST_PURCHASED_AT DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'"

}